Add CentOS imagestreams tests
sclorg/helm-charts pull request #50
Opened 2023-08-17 08:57 UTC by adobes1

Add tests for the following CentOS imagestream helm-charts: 
httpd, mariadb, mysql, nginx, nodejs, perl, php, postgresql, python, redis, ruby, varnish

2023-08-21 10:38 UTC, phracek requested changes
Thank you for this pull request. Please address my changes.

2023-08-21 10:38 UTC, phracek commented on tests/test_httpd_imagestreams.py
> +            ("2.4-ubi9", "registry.access.redhat.com/ubi9/httpd-24:latest"),
This is a part of TestHelmRHELHttpdImageStreams in CentOS should not be there.

2023-08-21 10:38 UTC, phracek commented on tests/test_nodejs_imagestreams.py
> +            ("16-ubi9", "registry.access.redhat.com/ubi9/nodejs-16:latest"),
The same here. CentOS are missing.

2023-08-21 12:06 UTC, phracek commented
@adobes1 Please rebase this pull request agains `main` branch.

2023-08-21 13:16 UTC, adobes1 commented
Thank you, rebased.

2023-08-22 09:47 UTC, adobes1 commented
[test]

2023-08-23 09:08 UTC, phracek commented
[test]

2023-08-23 10:36 UTC, merged